INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CDJ', 'Conceição do Araguaia Airport', 'Conceicao Do Araguaia');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('AQA', 'Araraquara Airport', 'Araracuara');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('AJU', 'Santa Maria Airport', 'Aracaju');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('AFL', 'Piloto Osvaldo Marques Dias Airport', 'Alta Floresta');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('ARU', 'Araçatuba Airport', 'Aracatuba');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('BEL', 'Val de Cans/Júlio Cezar Ribeiro International Airport', 'Belem');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('BGX', 'Comandante Gustavo Kraemer Airport', 'Bage');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('PLU', 'Pampulha - Carlos Drummond de Andrade Airport', 'Belo Horizonte');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('BFH', 'Bacacheri Airport', 'Curitiba');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('BSB', 'Presidente Juscelino Kubistschek International Airport', 'Brasilia');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('BAU', 'Bauru Airport', 'Bauru');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('BVB', 'Atlas Brasil Cantanhede Airport', 'Boa Vista');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CAC', 'Cascavel Airport', 'Cascavel');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CNF', 'Tancredo Neves International Airport', 'Belo Horizonte');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CGR', 'Campo Grande Airport', 'Campo Grande');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('XAP', 'Serafin Enoss Bertaso Airport', 'Chapeco');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CLN', 'Brig. Lysias Augusto Rodrigues Airport', 'Carolina');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CCM', 'Diomício Freitas Airport', 'Criciuma');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CAW', 'Bartolomeu Lisandro Airport', 'Campos');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CMG', 'Corumbá International Airport', 'Corumba');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CWB', 'Afonso Pena Airport', 'Curitiba');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CRQ', 'Caravelas Airport', 'Caravelas');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CXJ', 'Hugo Cantergiani Regional Airport', 'Caxias Do Sul');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CGB', 'Marechal Rondon Airport', 'Cuiaba');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CZS', 'Cruzeiro do Sul Airport', 'Cruzeiro do Sul');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('PPB', 'Presidente Prudente Airport', 'President Prudente');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('MAO', 'Eduardo Gomes International Airport', 'Manaus');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('IGU', 'Cataratas International Airport', 'Foz Do Iguacu');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('FLN', 'Hercílio Luz International Airport', 'Florianopolis');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('FEN', 'Fernando de Noronha Airport', 'Fernando Do Noronha');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('FOR', 'Pinto Martins International Airport', 'Fortaleza');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('GIG', 'Rio Galeão – Tom Jobim International Airport', 'Rio De Janeiro');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('GYN', 'Santa Genoveva Airport', 'Goiania');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('GRU', 'Guarulhos - Governador André Franco Montoro International Airport', 'Sao Paulo');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('ATM', 'Altamira Airport', 'Altamira');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('ITB', 'Itaituba Airport', 'Itaituba');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('IOS', 'Bahia - Jorge Amado Airport', 'Ilheus');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('IPN', 'Usiminas Airport', 'Ipatinga');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('IMP', 'Prefeito Renato Moreira Airport', 'Imperatriz');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('JDF', 'Francisco de Assis Airport', 'Juiz De Fora');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('JPA', 'Presidente Castro Pinto International Airport', 'Joao Pessoa');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('JOI', 'Lauro Carneiro de Loyola Airport', 'Joinville');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CPV', 'Presidente João Suassuna Airport', 'Campina Grande');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('VCP', 'Viracopos International Airport', 'Campinas');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('LIP', 'Lins Airport', 'Lins');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('LDB', 'Governador José Richa Airport', 'Londrina');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('LAZ', 'Bom Jesus da Lapa Airport', 'Bom Jesus Da Lapa');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('MAB', 'João Correa da Rocha Airport', 'Maraba');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('MGF', 'Regional de Maringá - Sílvio Nane Junior Airport', 'Maringa');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('MOC', 'Mário Ribeiro Airport', 'Montes Claros');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('PLL', 'Ponta Pelada Airport', 'Manaus');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('MCZ', 'Zumbi dos Palmares Airport', 'Maceio');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('MCP', 'Alberto Alcolumbre Airport', 'Macapa');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('MVF', 'Dix-Sept Rosado Airport', 'Mocord');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('MNX', 'Manicoré Airport', 'Manicore');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('NVT', 'Ministro Victor Konder International Airport', 'Navegantes');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('GEL', 'Santo Ângelo Airport', 'Santo Angelo');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('NAT', 'Governador Aluízio Alves International Airport', 'Natal');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('POA', 'Salgado Filho Airport', 'Porto Alegre');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('POO', 'Poços de Caldas - Embaixador Walther Moreira Salles Airport', 'Pocos De Caldas');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('PFB', 'Lauro Kurtz Airport', 'Passo Fundo');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('PET', 'João Simões Lopes Neto International Airport', 'Pelotas');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('PNZ', 'Senador Nilo Coelho Airport', 'Petrolina');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('PNB', 'Porto Nacional Airport', 'Porto Nacional');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('PMG', 'Ponta Porã Airport', 'Ponta Pora');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('PVH', 'Governador Jorge Teixeira de Oliveira Airport', 'Porto Velho');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('RBR', 'Plácido de Castro Airport', 'Rio Branco');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('REC', 'Guararapes - Gilberto Freyre International Airport', 'Recife');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('SDU', 'Santos Dumont Airport', 'Rio De Janeiro');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('RAO', 'Leite Lopes Airport', 'Ribeirao Preto');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('STU', 'Santa Cruz Airport', 'Rio De Janeiro');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('SJK', 'Professor Urbano Ernesto Stumpf Airport', 'Sao Jose Dos Campos');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('SLZ', 'Marechal Cunha Machado International Airport', 'Sao Luis');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CGH', 'Congonhas Airport', 'Sao Paulo');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('SJP', 'Prof. Eribelto Manoel Reino State Airport', 'Sao Jose Do Rio Preto');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('SSZ', 'Base Aérea de Santos Airport', 'Santos');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('SSA', 'Deputado Luiz Eduardo Magalhães International Airport', 'Salvador');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('TMT', 'Trombetas Airport', 'Oriximina');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('THE', 'Senador Petrônio Portela Airport', 'Teresina');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('TFF', 'Tefé Airport', 'Tefe');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('TBT', 'Tabatinga Airport', 'Tabatinga');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('TUR', 'Tucuruí Airport', 'Tucurui');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('SJL', 'São Gabriel da Cachoeira Airport', 'Sao Gabriel');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('PAV', 'Paulo Afonso Airport', 'Paulo Alfonso');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('URG', 'Rubem Berta Airport', 'Uruguaiana');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('UDI', 'Ten. Cel. Aviador César Bombonato Airport', 'Uberlandia');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('UBA', 'Mário de Almeida Franco Airport', 'Uberaba');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('VAG', 'Major Brigadeiro Trompowsky Airport', 'Varginha');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('BVH', 'Brigadeiro Camarão Airport', 'Vilhena');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('VIX', 'Eurico de Aguiar Salles Airport', 'Vitoria');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('QPS', 'Campo Fontenelle Airport', 'Piracununga');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('STM', 'Maestro Wilson Fonseca Airport', 'Santarem');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('BPS', 'Porto Seguro Airport', 'Porto Seguro');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('PMW', 'Brigadeiro Lysias Rodrigues Airport', 'Palmas');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CLV', 'Nelson Ribeiro Guimarães Airport', 'Caldas Novas');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('JDO', 'Orlando Bezerra de Menezes Airport', 'Juazeiro Do Norte');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('LEC', 'Coronel Horácio de Mattos Airport', 'Lençóis');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('MEA', 'Macaé Airport', 'Macaé');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('MII', 'Frank Miloye Milenkowichi–Marília State Airport', 'Marília');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('VDC', 'Vitória da Conquista Airport', 'Vitória Da Conquista');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('RIA', 'Santa Maria Airport', 'Santa Maria');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('TOW', 'Toledo Airport', 'Toledo');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('SOD', 'Sorocaba Airport', 'Sorocaba');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('MVS', 'Mucuri Airport', 'Mucuri');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('SRA', 'Santa Rosa Airport', 'Santa Rosa');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('JPR', 'Ji-Paraná Airport', 'Ji-Paraná');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('ERM', 'Erechim Airport', 'Erechim');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('GVR', 'Coronel Altino Machado de Oliveira Airport', 'Governador Valadares');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CPQ', 'Amarais Airport', 'Campinas');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CFB', 'Cabo Frio Airport', 'Cabo Frio');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('OPS', 'Presidente João Batista Figueiredo Airport', 'Sinop');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('GRP', 'Gurupi Airport', 'Gurupi');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CMP', 'Santana do Araguaia Airport', 'Santana do Araguaia');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('BVS', 'Breves Airport', 'Breves');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('SFK', 'Soure Airport', 'Soure');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('PIN', 'Parintins Airport', 'Parintins');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('BRA', 'Barreiras Airport', 'Barreiras');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('STZ', 'Santa Terezinha Airport', 'Santa Terezinha');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('MQH', 'Minaçu Airport', 'Minacu');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('AUX', 'Araguaína Airport', 'Araguaina');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('NVP', 'Novo Aripuanã Airport', 'Novo Aripuana');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('LVR', 'Fazenda Colen Airport', 'Lucas do Rio Verde');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('FRC', 'Franca Airport', 'Franca');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('DOU', 'Dourados Airport', 'Dourados');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('LBR', 'Lábrea Airport', 'Labrea');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('ROO', 'Maestro Marinho Franco Airport', 'Rondonopolis');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('GPB', 'Tancredo Thomas de Faria Airport', 'Guarapuava');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('JCB', 'Santa Terezinha Airport', 'Joacaba');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('RVD', 'General Leite de Castro Airport', 'Rio Verde');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('AAX', 'Romeu Zema Airport', 'Araxa');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('MBZ', 'Maués Airport', 'Maues');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('RBB', 'Borba Airport', 'Borba');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CIZ', 'Coari Airport', 'Coari');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('BAZ', 'Barcelos Airport', 'Barcelos');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('DMT', 'Diamantino Airport', 'Diamantino');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('GNM', 'Guanambi Airport', 'Guanambi');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CKS', 'Carajás Airport', 'Parauapebas');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('VAL', 'Valença Airport', 'Valenca');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CAU', 'Caruaru Airport', 'Caruaru');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('QNV', 'Aeroclube Airport', 'Nova Iguacu');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('BNU', 'Blumenau Airport', 'BLUMENAU');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('IZA', 'Zona da Mata Regional Airport', 'Juiz de Fora');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('POJ', 'Patos de Minas Airport', 'Patos de Minas');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('JTC', 'Bauru - Arealva Airport', 'Bauru');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('OIA', 'Ourilândia do Norte Airport', 'Ourilandia do Norte');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('RDC', 'Redenção Airport', 'Redencao');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('SXX', 'São Félix do Xingu Airport', 'Sao Felix do Xingu');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('BYO', 'Bonito Airport', 'Bointo');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('SXO', 'São Félix do Araguaia Airport', 'Sao Felix do Araguaia');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CFC', 'Caçador Airport', 'Cacador');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CAF', 'Carauari Airport', 'Carauari');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('ERN', 'Eirunepé Airport', 'Eirunepe');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CCI', 'Concórdia Airport', 'Concordia');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('FBE', 'Francisco Beltrão Airport', 'Francisco Beltrao');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CFO', 'Confresa Airport', 'Confresa');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('UMU', 'Umuarama Airport', 'Umuarama');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('DTI', 'Diamantina Airport', 'Diamantina');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('FBA', 'Fonte Boa Airport', 'Fonte Boa');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('OLC', 'Senadora Eunice Micheles Airport', 'Sao Paulo de Olivenca');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('HUW', 'Humaitá Airport', 'Humaita');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('IRZ', 'Tapuruquara Airport', 'Santa Isabel do Rio Negro');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('ORX', 'Oriximiná Airport', 'Oriximina');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('UNA', 'Hotel Transamérica Airport', 'Una');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('QCJ', 'Botucatu - Tancredo de Almeida Neves Airport', 'Botucatu');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('QSC', 'São Carlos Airport', 'Sao Carlos');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('BJP', 'Estadual Arthur Siqueira Airport', 'Braganca Paulista');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('TJL', 'Plínio Alarcom Airport', 'Tres Lagoas');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('OAL', 'Cacoal Airport', 'Cacoal');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('PPY', 'Pouso Alegre Airport', 'Pouso Alegre');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('DIQ', 'Brigadeiro Cabral Airport', 'Divinopolis');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('GUZ', 'Guarapari Airport', 'Guarapari');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('UBT', 'Ubatuba Airport', 'Ubatuba');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('TFL', 'Juscelino Kubitscheck Airport', 'Teofilo Otoni');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('BZC', 'Umberto Modiano Airport', 'Buzios');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('ITP', 'Itaperuna Airport', 'Itaperuna');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('AIR', 'Aripuanã Airport', 'Aripuana');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('JRN', 'Juruena Airport', 'Juruena');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('JIA', 'Juína Airport', 'Juina');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('VLP', 'Vila Rica Airport', 'Vila Rica');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('JUA', 'Inácio Luís do Nascimento Airport', 'Juara');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('CCX', 'Cáceres Airport', 'Caceres');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('QBX', 'Sobral Airport', 'Sobral');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('APQ', 'Arapiraca Airport', 'Arapiraca');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('FLB', 'Cangapara Airport', 'Floriano');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('PCS', 'Picos Airport', 'Picos');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('SQX', 'São Miguel do Oeste Airport', 'Sao Miguel do Oeste');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('BAT', 'Chafei Amsei Airport', 'Barretos');
INSERT INTO aeroporto (iata, nome, cidade) VALUES ('QHP', 'Base de Aviação de Taubaté Airport', 'Taubaté');
